### ISSUE TITLE
Request README update with performance characteristics and internal operation

### ISSUE THREAD

**Issue by nous-** [mehcode/actix-diesel#2]
Hello,

I am seeking the the type-safety of Diesel with the performance of actix-pg.

Are the internals of this library ushering calls out to synchronous actors to do standard diesel blocking calls? What are its performance characteristics? It would be helpful to have these details added to the README.

Thank you for your contribution to the community.

**Comment by mehcode** [comment]
In short, Diesel is synchronous. There is nothing we can do from **outside** Diesel to affect that. This is using `SyncActor` from Actix to spawn database worker threads and communicating results back through futures.

---

I'll accept a pull request that annotates this. I don't have the time myself to do much here. This was more an experiment. I've moved away from Actix going forward myself.

**Comment by ITwrx** [comment]
@mehcode I'm new to rust and evaluating things. If you've moved away from Actix what are you planning on using going forward?
thanks

**Comment by mehcode** [comment]
I currently use https://github.com/http-rs/tide/ with https://github.com/launchbadge/sqlx

**Comment by ITwrx** [comment]
thanks a lot.
